### ISSUE TITLE
Update Covid Search Parameters

### ISSUE THREAD

**Issue by jrsparl** [Napo-100/Covid-travel-safety-app#10]
Currently the covid API search is broken since we are no long using the drop down menus.  We need to build a function using the current location search parameters to pull the covid information. Below are all the functions you can use to retrieve location search information:

*Pulls the city name from local storage*
cityName = getCityName(); 

*Pulls the full state name ie "Florida" unless it is international which it will return "Null" (capital N)*
longStateName = getStateLong();  

*Pulls the state abbrev ie "FL" unless it is international which it will return "Null" (capital N)*
ShortStateName = getStateShort();  

*Pulls the countrycode ie "US"*
ShortCountryName = getCountryShort (); 

*Pulls the full country name ie "United States of America"*
LongCountryName = getCountryLong();

**Comment by johngeorge88** [comment]
we just need to fix the clickCity function
